import { Sparkles, Info } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { InsightGrid } from "@/components/insights/InsightCard";
import { detectSignals } from "@/lib/insights/signals";
import { normalizeReportData } from "@/lib/report";
import { HelpHint } from "@/components/ui/help-hint";

/**
 * The AI analysis that accompanies every report.
 *
 * Two clearly separated halves, which is the point:
 *   1. the model's written summary — prose, labelled as AI-written
 *   2. derived signals — arithmetic over the client's own rows
 *
 * Keeping them visually distinct is what makes the whole thing trustworthy. A
 * reader can see which claims are generated language and which are measured
 * facts, instead of having to take one undifferentiated block on faith.
 *
 * Renders nothing at all when there is neither a summary nor a signal — an
 * empty "AI Insights" heading would imply the analysis ran and found nothing,
 * when in reality the data simply wasn't there.
 */
export function AiAnalysisPanel({ data, compact = false }: { data: unknown; compact?: boolean }) {
  const { gsc, ga4, insights } = normalizeReportData(data);
  const signals = detectSignals(gsc, ga4, compact ? 3 : 6);
  const summary = insights?.executiveSummary?.trim() || null;
  const actions = (insights?.recommendedActions ?? []).filter((a) => a.trim()).slice(0, 4);

  if (!summary && signals.length === 0 && actions.length === 0) return null;

  return (
    <Card className="no-print overflow-hidden">
      <CardContent className="p-6">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <h2 className="flex items-center gap-2 text-base font-semibold tracking-tight text-ink-900">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-brand-50 text-brand-600">
              <Sparkles size={15} aria-hidden />
            </span>
            AI analysis
            <HelpHint label="How this analysis is produced">
              The written summary is generated by an AI model from this client&apos;s synced numbers. The insight cards
              below it are calculated directly from the same data — not written by the model — so every figure traces
              back to a row Search Console or Analytics returned.
            </HelpHint>
          </h2>
          <span className="rounded-full bg-surface-muted px-2.5 py-1 text-[11px] font-medium text-ink-500">
            From this client&apos;s own data
          </span>
        </div>

        {summary && (
          <div className="mt-4 rounded-xl border border-brand-100 bg-brand-50/40 p-4">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-brand-700">Executive summary</p>
            <p className="mt-1.5 text-sm leading-relaxed text-ink-800">{summary}</p>
            <p className="mt-2 text-[11px] text-ink-500">AI-written from the metrics in this report.</p>
          </div>
        )}

        {signals.length > 0 && (
          <div className="mt-5">
            <p className="mb-2.5 text-[11px] font-semibold uppercase tracking-wide text-ink-400">
              What the numbers show
            </p>
            <InsightGrid signals={signals} />
          </div>
        )}

        {actions.length > 0 && (
          <div className="mt-5">
            <p className="mb-2.5 text-[11px] font-semibold uppercase tracking-wide text-ink-400">Recommended next steps</p>
            <ol className="space-y-2">
              {actions.map((a, i) => (
                <li key={i} className="flex gap-2.5 rounded-xl border border-ink-100 bg-surface-muted/40 px-3.5 py-2.5">
                  <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-brand-solid text-[11px] font-semibold text-white">
                    {i + 1}
                  </span>
                  <span className="text-sm leading-relaxed text-ink-700">{a}</span>
                </li>
              ))}
            </ol>
          </div>
        )}

        <p className="mt-5 flex items-start gap-1.5 border-t border-ink-100 pt-3 text-[11px] leading-relaxed text-ink-500">
          <Info size={12} className="mt-0.5 shrink-0" aria-hidden />
          Insights describe what the data shows for this period. They aren&apos;t predictions, and confidence reflects
          sample size — not certainty about the future.
        </p>
      </CardContent>
    </Card>
  );
}
