import Link from "next/link";
import {
  Check, X, Sparkles, Palette, Zap, Clock, Users, FileBarChart2, Plug,
  ArrowRight, ShieldCheck, MousePointerClick, Eye, TrendingUp, Star,
} from "lucide-react";
import { Brand } from "@/components/Brand";
import { SiteFooter } from "@/components/SiteFooter";

export const metadata = {
  title: "ReportFlow — White-label client reports, generated by AI",
  description:
    "Stop building client reports by hand. ReportFlow pulls your marketing data, writes the insights with AI, and delivers beautiful white-label reports — flat price, unlimited clients.",
};

const navLinks = [
  { label: "How it works", href: "#how" },
  { label: "Features", href: "#features" },
  { label: "Compare", href: "#compare" },
  { label: "Pricing", href: "#pricing" },
  { label: "FAQ", href: "#faq" },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white text-ink-900">
      {/* ── Nav ── */}
      <header className="sticky top-0 z-30 border-b border-slate-100 bg-white/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-3.5">
          <Brand className="text-lg" />
          <nav className="hidden items-center gap-7 text-sm text-ink-600 md:flex">
            {navLinks.map((l) => (
              <a key={l.href} href={l.href} className="hover:text-ink-900">{l.label}</a>
            ))}
          </nav>
          <div className="flex items-center gap-3 text-sm">
            <Link href="/login" className="hidden text-ink-700 hover:text-ink-900 sm:inline">Sign in</Link>
            <Link href="/signup" className="rounded-lg bg-brand-500 px-4 py-2 font-medium text-white hover:bg-brand-600">Start free</Link>
          </div>
        </div>
      </header>

      {/* ── 1. Hero ── */}
      <section className="relative overflow-hidden">
        <div className="pointer-events-none absolute inset-x-0 top-0 h-[420px] bg-gradient-to-b from-brand-50 to-white" />
        <div className="relative mx-auto max-w-6xl px-5 pb-10 pt-16 text-center sm:pt-20">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-brand-100 bg-white px-3 py-1 text-xs font-medium text-brand-700">
            <Sparkles size={13} /> AI-powered client reporting for agencies
          </span>
          <h1 className="mx-auto mt-6 max-w-3xl text-4xl font-semibold leading-[1.1] tracking-tight sm:text-6xl">
            Client reports that used to take hours,<span className="text-brand-600"> done in minutes.</span>
          </h1>
          <p className="mx-auto mt-6 max-w-xl text-lg text-ink-500">
            ReportFlow pulls your marketing data, writes the insights with AI, and delivers beautiful
            white-label reports — <span className="font-medium text-ink-700">flat price, unlimited clients,</span> zero dashboards to learn.
          </p>
          <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <Link href="/signup" className="inline-flex items-center gap-2 rounded-lg bg-brand-500 px-6 py-3 font-medium text-white shadow-sm transition hover:bg-brand-600">
              Start free — no card required <ArrowRight size={18} />
            </Link>
            <Link href="/dashboard/reports/preview" className="rounded-lg border border-slate-200 px-6 py-3 font-medium text-ink-700 hover:bg-slate-50">
              See a sample report
            </Link>
          </div>
          <p className="mt-4 text-xs text-ink-400">14-day free trial · Setup in under 5 minutes · Cancel anytime</p>

          {/* 2. Dashboard / report preview mock */}
          <div className="relative mx-auto mt-12 max-w-4xl">
            <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl shadow-brand-500/5">
              <ReportMock />
            </div>
          </div>
        </div>
      </section>

      {/* trust strip */}
      <section className="border-y border-slate-100 bg-slate-50/60">
        <div className="mx-auto grid max-w-5xl grid-cols-2 gap-6 px-5 py-7 text-center sm:grid-cols-4">
          {[
            { v: "5 min", l: "to first report" },
            { v: "∞", l: "clients, one flat price" },
            { v: "AI", l: "insights on every report" },
            { v: "100%", l: "your branding" },
          ].map((s) => (
            <div key={s.l}>
              <p className="text-2xl font-semibold text-brand-600">{s.v}</p>
              <p className="mt-0.5 text-xs text-ink-500">{s.l}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── 3. How it works ── */}
      <section id="how" className="mx-auto max-w-6xl px-5 py-20">
        <SectionHeading eyebrow="How it works" title="From data to client-ready report in three steps" subtitle="No spreadsheets, no screenshots, no copy-pasting." />
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          {[
            { icon: Plug, title: "Connect a data source", text: "Link a client's Google Search Console in two clicks. GA4, Google Ads and more are on the way." },
            { icon: Sparkles, title: "ReportFlow does the work", text: "We pull the metrics, build the charts, and write plain-English insights and recommendations with AI." },
            { icon: FileBarChart2, title: "Send a branded report", text: "Share a live link or export a PDF — under your logo, your colours, your domain." },
          ].map((s, i) => {
            const Icon = s.icon;
            return (
              <div key={i} className="relative rounded-2xl border border-slate-200 p-6">
                <span className="absolute right-5 top-5 text-4xl font-bold text-slate-100">{i + 1}</span>
                <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Icon size={20} /></div>
                <h3 className="mt-4 font-semibold text-ink-900">{s.title}</h3>
                <p className="mt-1.5 text-sm text-ink-500">{s.text}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* ── 4. Key benefits ── */}
      <section id="features" className="bg-slate-50/60 py-20">
        <div className="mx-auto max-w-6xl px-5">
          <SectionHeading eyebrow="Why agencies switch" title="Built to kill the parts of reporting you hate" subtitle="Every feature targets the time-sink and the bloat of legacy tools." />
          <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { icon: Clock, title: "No more manual reporting", text: "Stop rebuilding the same report every month. ReportFlow refreshes the data and writes the narrative for you." },
              { icon: Users, title: "Flat price, unlimited clients", text: "Add your 5th or 50th client at no extra cost. No per-client fees that punish you for growing." },
              { icon: Zap, title: "Live in 5 minutes", text: "Connect, pick a property, generate. No onboarding calls, no 100-widget dashboards to configure." },
              { icon: Sparkles, title: "AI insights, not just charts", text: "Clients want to know what the numbers mean. Every report explains wins, risks and next steps in plain English." },
              { icon: Palette, title: "Truly white-label", text: "Your logo, brand colour, footer and domain on every report. Clients never see ReportFlow." },
              { icon: ShieldCheck, title: "Clean, modern UX", text: "A reporting tool that looks as good as the work you do — no clutter, no learning curve." },
            ].map((b, i) => {
              const Icon = b.icon;
              return (
                <div key={i} className="rounded-2xl border border-slate-200 bg-white p-6">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-brand-50 text-brand-600"><Icon size={18} /></div>
                  <h3 className="mt-4 font-semibold text-ink-900">{b.title}</h3>
                  <p className="mt-1.5 text-sm text-ink-500">{b.text}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── 5. Competitor comparison ── */}
      <section id="compare" className="mx-auto max-w-5xl px-5 py-20">
        <SectionHeading eyebrow="How we compare" title="The same reports, without the price tag or the bloat" subtitle="Why agencies move to ReportFlow from AgencyAnalytics and Whatagraph." />
        <div className="mt-12 overflow-x-auto">
          <table className="w-full min-w-[600px] border-separate border-spacing-0 text-sm">
            <thead>
              <tr>
                <th className="w-[34%] p-4 text-left font-medium text-ink-500"></th>
                <th className="rounded-t-xl bg-brand-500 p-4 text-center font-semibold text-white">ReportFlow</th>
                <th className="p-4 text-center font-medium text-ink-600">AgencyAnalytics</th>
                <th className="p-4 text-center font-medium text-ink-600">Whatagraph</th>
              </tr>
            </thead>
            <tbody>
              {[
                { f: "Flat price, unlimited clients", a: true, b: false, c: false },
                { f: "AI-written insights & recommendations", a: true, b: false, c: false },
                { f: "Setup in minutes", a: true, b: false, c: false },
                { f: "Fully white-label reports", a: true, b: true, c: true },
                { f: "No per-client fees", a: true, b: false, c: false },
                { f: "Simple, modern UX (no dashboard maze)", a: true, b: false, c: false },
              ].map((r, i, arr) => (
                <tr key={r.f}>
                  <td className="border-b border-slate-100 p-4 text-left text-ink-700">{r.f}</td>
                  <td className={`border-x border-brand-100 bg-brand-50/40 p-4 text-center ${i === arr.length - 1 ? "rounded-b-xl border-b" : ""}`}>
                    <Cell on={r.a} />
                  </td>
                  <td className="border-b border-slate-100 p-4 text-center"><Cell on={r.b} /></td>
                  <td className="border-b border-slate-100 p-4 text-center"><Cell on={r.c} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="mt-4 text-center text-xs text-ink-400">Comparison reflects typical positioning of each product; competitor plans and features change over time.</p>
      </section>

      {/* ── 6. AI insights showcase ── */}
      <section className="bg-slate-50/60 py-20">
        <div className="mx-auto grid max-w-6xl items-center gap-12 px-5 lg:grid-cols-2">
          <div>
            <span className="inline-flex items-center gap-1.5 rounded-full bg-brand-50 px-3 py-1 text-xs font-medium text-brand-700"><Sparkles size={13} /> AI insights</span>
            <h2 className="mt-4 text-3xl font-semibold tracking-tight">Your clients want answers, not just charts</h2>
            <p className="mt-4 text-ink-500">
              Every report includes a plain-English executive summary, the month&apos;s key wins and risks, and prioritised recommendations — written automatically from the real data. Turn raw metrics into a story your client actually reads.
            </p>
            <ul className="mt-6 space-y-3">
              {["Executive summary in seconds", "Winning & declining keywords surfaced automatically", "Clear, prioritised next-step recommendations"].map((t) => (
                <li key={t} className="flex items-center gap-2.5 text-sm text-ink-700"><Check size={16} className="text-brand-600" /> {t}</li>
              ))}
            </ul>
          </div>
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <div className="mb-3 flex items-center gap-2 text-sm font-semibold text-brand-600"><Sparkles size={15} /> AI summary</div>
            <p className="text-sm leading-relaxed text-ink-700">
              “Organic clicks are up <span className="font-semibold text-emerald-600">18%</span> and impressions <span className="font-semibold text-emerald-600">12%</span> this month, led by &lsquo;carbon plate running shoes&rsquo; at position 2.1. Average position improved from 11.4 to 9.8.”
            </p>
            <div className="mt-4 space-y-2">
              {[
                { t: "Win", c: "bg-emerald-50 text-emerald-700", x: "“Carbon plate shoes” up 142%." },
                { t: "Watch", c: "bg-rose-50 text-rose-600", x: "“Cheap running shoes” down 38%." },
                { t: "Next", c: "bg-amber-50 text-amber-700", x: "Build a beginners page — one spot off page one." },
              ].map((r) => (
                <div key={r.t} className="flex items-center gap-2 text-xs">
                  <span className={`rounded-full px-2 py-0.5 font-semibold ${r.c}`}>{r.t}</span>
                  <span className="text-ink-600">{r.x}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── 7. White-label showcase ── */}
      <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-20 lg:grid-cols-2">
        <div className="order-2 lg:order-1">
          <div className="overflow-hidden rounded-2xl border border-slate-200 shadow-sm">
            <div className="flex items-center gap-3 px-6 py-6 text-white" style={{ background: "linear-gradient(135deg,#4f46e5,#3730a3)" }}>
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white/95 text-sm font-bold text-brand-600">A</div>
              <span className="font-semibold">Your Agency</span>
              <span className="ml-auto rounded-full bg-white/15 px-2.5 py-1 text-[11px] font-medium">SEO Report</span>
            </div>
            <div className="space-y-3 p-6">
              <div className="grid grid-cols-3 gap-2">
                {["Clicks", "Impressions", "Avg Pos"].map((k) => (
                  <div key={k} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] text-ink-500">{k}</p><div className="mt-1 h-4 w-12 rounded bg-brand-100" /></div>
                ))}
              </div>
              <div className="flex items-end gap-1.5">
                {[40, 55, 48, 70, 62, 85, 78].map((h, i) => <div key={i} className="flex-1 rounded-t bg-brand-500/80" style={{ height: h }} />)}
              </div>
            </div>
          </div>
        </div>
        <div className="order-1 lg:order-2">
          <span className="inline-flex items-center gap-1.5 rounded-full bg-brand-50 px-3 py-1 text-xs font-medium text-brand-700"><Palette size={13} /> White-label</span>
          <h2 className="mt-4 text-3xl font-semibold tracking-tight">It&apos;s your brand on every report — not ours</h2>
          <p className="mt-4 text-ink-500">
            Upload your logo, set your brand colour, add your footer and send from your own domain. Clients see a polished report from <span className="font-medium text-ink-700">your agency</span> — ReportFlow stays invisible.
          </p>
          <ul className="mt-6 space-y-3">
            {["Your logo, colours & footer", "Send from your verified domain", "Shareable live link or PDF export"].map((t) => (
              <li key={t} className="flex items-center gap-2.5 text-sm text-ink-700"><Check size={16} className="text-brand-600" /> {t}</li>
            ))}
          </ul>
        </div>
      </section>

      {/* ── 8. Integrations ── */}
      <section className="bg-slate-50/60 py-20">
        <div className="mx-auto max-w-6xl px-5">
          <SectionHeading eyebrow="Integrations" title="Connect the platforms your clients live on" subtitle="Start with Search Console today. More sources are rolling out fast." />
          <div className="mx-auto mt-12 grid max-w-4xl grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">
            {[
              { n: "Search Console", live: true, icon: MousePointerClick },
              { n: "Google Analytics 4", live: false, icon: TrendingUp },
              { n: "Google Ads", live: false, icon: Zap },
              { n: "Facebook Ads", live: false, icon: Eye },
              { n: "LinkedIn Ads", live: false, icon: Users },
            ].map((it) => {
              const Icon = it.icon;
              return (
                <div key={it.n} className="rounded-xl border border-slate-200 bg-white p-4 text-center">
                  <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-brand-50 text-brand-600"><Icon size={18} /></div>
                  <p className="mt-3 text-sm font-medium text-ink-800">{it.n}</p>
                  <span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[10px] font-semibold ${it.live ? "bg-emerald-50 text-emerald-600" : "bg-slate-100 text-ink-400"}`}>{it.live ? "Live" : "Coming soon"}</span>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── 9. Testimonials ── */}
      <section className="mx-auto max-w-6xl px-5 py-20">
        <SectionHeading eyebrow="Loved by lean agencies" title="More billable hours, fewer reporting headaches" subtitle="" />
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          {[
            { q: "We cut monthly reporting from two full days to about twenty minutes. The AI summaries alone are worth it.", n: "Founder", a: "3-person SEO studio" },
            { q: "Switching off per-client pricing saved us hundreds a month. Now adding a client costs us nothing.", n: "Owner", a: "PPC agency" },
            { q: "Clients think we built a custom reporting platform. It's just ReportFlow under our brand.", n: "Director", a: "Growth agency" },
          ].map((t, i) => (
            <figure key={i} className="rounded-2xl border border-slate-200 bg-white p-6">
              <div className="flex gap-0.5 text-amber-400">{Array.from({ length: 5 }).map((_, j) => <Star key={j} size={14} fill="currentColor" />)}</div>
              <blockquote className="mt-3 text-sm leading-relaxed text-ink-700">“{t.q}”</blockquote>
              <figcaption className="mt-4 flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-100 text-xs font-semibold text-brand-700">{t.n.charAt(0)}</div>
                <div><p className="text-sm font-medium text-ink-800">{t.n}</p><p className="text-xs text-ink-400">{t.a}</p></div>
              </figcaption>
            </figure>
          ))}
        </div>
        <p className="mt-4 text-center text-xs text-ink-400">Illustrative quotes shown during launch.</p>
      </section>

      {/* ── 10. Pricing ── */}
      <section id="pricing" className="bg-slate-50/60 py-20">
        <div className="mx-auto max-w-5xl px-5">
          <SectionHeading eyebrow="Pricing" title="One flat price. Unlimited clients. Everything included." subtitle="No per-client fees. No feature gates that matter. Cancel anytime." />
          <div className="mx-auto mt-12 grid max-w-3xl gap-6 sm:grid-cols-2">
            {/* Trial */}
            <div className="rounded-2xl border border-slate-200 bg-white p-7">
              <p className="text-sm font-medium text-ink-500">Free trial</p>
              <p className="mt-2 text-4xl font-semibold">$0</p>
              <p className="mt-1 text-sm text-ink-400">14 days, no card required</p>
              <Link href="/signup" className="mt-6 block rounded-lg border border-slate-200 px-5 py-3 text-center font-medium text-ink-700 hover:bg-slate-50">Start free</Link>
              <ul className="mt-6 space-y-2.5 text-sm text-ink-600">
                {["Full access to every feature", "Connect a real client", "Generate AI reports"].map((t) => <li key={t} className="flex items-center gap-2"><Check size={15} className="text-brand-600" /> {t}</li>)}
              </ul>
            </div>
            {/* Pro */}
            <div className="relative rounded-2xl border-2 border-brand-500 bg-white p-7 shadow-lg shadow-brand-500/10">
              <span className="absolute -top-3 left-7 rounded-full bg-brand-500 px-3 py-1 text-xs font-semibold text-white">Most popular</span>
              <p className="text-sm font-medium text-ink-500">Agency</p>
              <p className="mt-2 text-4xl font-semibold">$49<span className="text-base font-normal text-ink-400">/mo</span></p>
              <p className="mt-1 text-sm text-ink-400">Flat — billed monthly, or $39/mo annually</p>
              <Link href="/signup" className="mt-6 block rounded-lg bg-brand-500 px-5 py-3 text-center font-medium text-white hover:bg-brand-600">Start free trial</Link>
              <ul className="mt-6 space-y-2.5 text-sm text-ink-700">
                {["Unlimited clients & reports", "AI insights on every report", "Full white-label branding", "Shareable links + PDF export", "All integrations as they launch"].map((t) => <li key={t} className="flex items-center gap-2"><Check size={15} className="text-brand-600" /> {t}</li>)}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* ── 11. FAQ ── */}
      <section id="faq" className="mx-auto max-w-3xl px-5 py-20">
        <SectionHeading eyebrow="FAQ" title="Questions, answered" subtitle="" />
        <div className="mt-10 divide-y divide-slate-100 rounded-2xl border border-slate-200">
          {[
            { q: "How is ReportFlow different from AgencyAnalytics or Whatagraph?", a: "Three things: flat pricing with unlimited clients (no per-client fees), AI-written insights on every report, and a setup measured in minutes instead of hours. We deliberately do less than the big dashboards — and do the reporting part far better." },
            { q: "Do you really not charge per client?", a: "Correct. One flat price covers unlimited clients and reports. Add your 50th client at no extra cost." },
            { q: "Is it actually white-label?", a: "Yes. Your logo, brand colour, footer and sending domain appear on every report. Your clients never see the ReportFlow name." },
            { q: "What data sources are supported?", a: "Google Search Console is live today. Google Analytics 4, Google Ads, Facebook Ads and LinkedIn Ads are rolling out — your feedback shapes the order." },
            { q: "How long does setup take?", a: "Under five minutes: create an account, connect a client's Search Console, pick a property, and generate your first AI report." },
            { q: "Can I export to PDF?", a: "Yes — share a live branded link or export a clean PDF for clients who want a file." },
          ].map((f, i) => (
            <details key={i} className="group p-5">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-medium text-ink-800">
                {f.q}
                <span className="text-ink-400 transition group-open:rotate-45">+</span>
              </summary>
              <p className="mt-3 text-sm leading-relaxed text-ink-500">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* ── 12. Final CTA ── */}
      <section className="mx-auto max-w-6xl px-5 pb-20">
        <div className="overflow-hidden rounded-3xl px-8 py-14 text-center text-white sm:px-16" style={{ background: "linear-gradient(135deg,#4f46e5,#3730a3)" }}>
          <h2 className="mx-auto max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Send your next client report in minutes</h2>
          <p className="mx-auto mt-4 max-w-xl text-white/80">Free for 14 days. No credit card. Connect a client and generate a fully branded, AI-written report today.</p>
          <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <Link href="/signup" className="inline-flex items-center gap-2 rounded-lg bg-white px-6 py-3 font-medium text-brand-700 hover:bg-white/90">Start free <ArrowRight size={18} /></Link>
            <Link href="/dashboard/reports/preview" className="rounded-lg border border-white/30 px-6 py-3 font-medium text-white hover:bg-white/10">See a sample report</Link>
          </div>
        </div>
      </section>

      {/* ── 13. Footer ── */}
      <SiteFooter />
    </div>
  );
}

/* ── helpers ── */
function SectionHeading({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle?: string }) {
  return (
    <div className="mx-auto max-w-2xl text-center">
      <p className="text-sm font-semibold text-brand-600">{eyebrow}</p>
      <h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h2>
      {subtitle && <p className="mt-3 text-ink-500">{subtitle}</p>}
    </div>
  );
}

function Cell({ on }: { on: boolean }) {
  return on
    ? <Check size={18} className="mx-auto text-emerald-600" />
    : <X size={18} className="mx-auto text-slate-300" />;
}

// Inline hero mock — a stylised report so the value is visible above the fold.
function ReportMock() {
  return (
    <div>
      <div className="flex items-center gap-3 px-6 py-5 text-white" style={{ background: "linear-gradient(135deg,#4f46e5,#3730a3)" }}>
        <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white/95 text-sm font-bold text-brand-600">A</div>
        <div className="text-left">
          <p className="text-sm font-semibold leading-tight">Acme Co — SEO Report</p>
          <p className="text-[11px] text-white/70">Prepared by Your Agency · Last 28 days</p>
        </div>
        <span className="ml-auto rounded-full bg-white/15 px-2.5 py-1 text-[11px] font-medium">Live</span>
      </div>
      <div className="grid grid-cols-2 gap-3 p-5 text-left sm:grid-cols-4">
        {[
          { l: "Clicks", v: "14,820", d: "+18%" },
          { l: "Impressions", v: "312k", d: "+12%" },
          { l: "Avg CTR", v: "4.7%", d: "+6%" },
          { l: "Avg Position", v: "9.8", d: "+13%" },
        ].map((m) => (
          <div key={m.l} className="rounded-xl border border-slate-100 bg-slate-50 p-3">
            <p className="text-[11px] text-ink-500">{m.l}</p>
            <p className="mt-0.5 text-lg font-semibold text-brand-600">{m.v}</p>
            <p className="text-[10px] font-medium text-emerald-600">▲ {m.d} vs prev.</p>
          </div>
        ))}
      </div>
      <div className="flex items-end gap-1.5 px-5 pb-3">
        {[34, 48, 42, 60, 52, 71, 64, 80, 73, 90].map((h, i) => <div key={i} className="flex-1 rounded-t bg-brand-500/70" style={{ height: h }} />)}
      </div>
      <div className="mx-5 mb-5 rounded-xl border border-brand-100 bg-brand-50/50 p-3 text-left">
        <p className="flex items-center gap-1.5 text-xs font-semibold text-brand-600"><Sparkles size={12} /> AI summary</p>
        <p className="mt-1 text-[11px] leading-relaxed text-ink-600">Organic clicks up 18% this month, led by premium product terms. Average position improved ~1.5 spots — momentum is building.</p>
      </div>
    </div>
  );
}
