import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell } from "@/components/LegalShell";
import { COMPANY, LEGAL_LAST_UPDATED } from "@/lib/company";

export const metadata: Metadata = {
  title: `Terms of Service — ${COMPANY.product}`,
  description: `The terms that govern your use of ${COMPANY.product}.`,
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      subtitle={`The agreement between you and ${COMPANY.product}.`}
      lastUpdated={LEGAL_LAST_UPDATED}
    >
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of {COMPANY.product}, operated by{" "}
        {COMPANY.legalName} (&quot;we&quot;, &quot;us&quot;). By creating an account or using the service you agree to
        these Terms and to our <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>1. The service</h2>
      <p>
        {COMPANY.product} is a white-label client-reporting platform: it connects to marketing data sources you
        authorize, generates branded reports (including AI-written summaries), and delivers them to your clients on
        the schedule you choose. We may improve or modify features over time.
      </p>

      <h2>2. Your account</h2>
      <ul>
        <li>You must provide accurate information and keep your credentials secure. You are responsible for activity under your account.</li>
        <li>You must be at least 16 years old and using the service for business purposes.</li>
        <li>One agency workspace is created per account; the data in it belongs to you.</li>
      </ul>

      <h2>3. Connected data sources</h2>
      <ul>
        <li>You may only connect accounts (e.g. Google Search Console, Google Analytics, Meta Ads) that you own or are authorized to access on a client&apos;s behalf.</li>
        <li>You are responsible for having the necessary permission from your clients to access and report on their data.</li>
        <li>Your use of connected platforms remains subject to those platforms&apos; own terms.</li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the service for unlawful purposes or in violation of third-party rights.</li>
        <li>Attempt to access other customers&apos; data, probe or disrupt the service, or circumvent security or rate limits.</li>
        <li>Resell or white-label the platform itself (your reports are white-label; the platform is not).</li>
        <li>Send spam or unlawful content through report-delivery emails.</li>
      </ul>

      <h2>5. Subscriptions and billing</h2>
      <ul>
        <li>Paid plans are billed through our merchant of record, Paddle, which handles payment processing and applicable taxes.</li>
        <li>Subscriptions renew automatically until cancelled. You can cancel any time; access continues to the end of the paid period.</li>
        <li>Trial periods, prices, and plan limits are described on the pricing page and may change with notice.</li>
      </ul>

      <h2>6. Intellectual property</h2>
      <ul>
        <li>You retain all rights to your data, your branding, and the reports generated for you.</li>
        <li>We retain all rights to the {COMPANY.product} software, design, and brand.</li>
        <li>You grant us the limited licence needed to process your data solely to provide the service.</li>
      </ul>

      <h2>7. AI-generated content</h2>
      <p>
        Report summaries and recommendations are generated by AI from your metrics. They are provided for convenience
        and may contain inaccuracies — review reports before relying on them or sending them to clients.
      </p>

      <h2>8. Availability and disclaimers</h2>
      <p>
        The service is provided <strong>&quot;as is&quot;</strong> and &quot;as available&quot;. We do not warrant
        uninterrupted operation, and we depend on third-party APIs (Google, Meta, and others) that may change or fail
        outside our control. To the maximum extent permitted by law, we disclaim all implied warranties.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, our total liability arising out of the service is limited to the
        amount you paid us in the twelve months before the claim. We are not liable for indirect, incidental, or
        consequential damages, or for loss of profits, revenue, or data.
      </p>

      <h2>10. Termination</h2>
      <p>
        You may stop using the service and request account deletion at any time. We may suspend or terminate accounts
        that violate these Terms, with notice where practicable. Sections that by their nature should survive
        termination (such as 6, 9, and 11) survive.
      </p>

      <h2>11. Governing law</h2>
      <p>These Terms are governed by the laws of {COMPANY.jurisdiction}, without regard to conflict-of-law rules.</p>

      <h2>12. Changes</h2>
      <p>
        We may update these Terms; material changes will be announced in the app or by email. Continued use after
        changes take effect constitutes acceptance.
      </p>

      <h2>13. Contact</h2>
      <p>
        {COMPANY.legalName}, {COMPANY.address} · <a href={`mailto:${COMPANY.supportEmail}`}>{COMPANY.supportEmail}</a>
      </p>
    </LegalShell>
  );
}
